version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2204:current

    steps:
      - checkout

      - run:
          name: Build Docker image
          command: docker build -t kavin/react-sample .

      - run:
          name: Run tests
          command: docker run kavin/react-sample npm run build

workflows:
  test-workflow:
    jobs:
      - test
